name: CI
on: [push, pull_request]

env:
  POETRY_HOME: '~/.local'
  POETRY_CACHE_DIR: '~/.local/.cache'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-20.04", "ubuntu-22.04", "macos-11", "macos-12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: make install-poetry
      - name: Install Packages
        run: make install
      - name: Run Tests
        run: make test
